# Writes the compiled-in string table the experimental Linux build's Fetch_String reads
# instead of loading Language.dll, which is a Windows resource-only PE DLL with no ELF
# equivalent. Reads language.rc's STRINGTABLE entries and language.h's TXT_ identifiers, and
# emits an id -> text array. Windows keeps loading Language.dll unchanged; this generated
# header is only compiled into the non-Windows Fetch_String path.
#
# Run at configure time and once per build, so an edit to language.rc reaches the table
# without a reconfigure. The header is only rewritten when its contents change, so an
# ordinary rebuild does not force a recompile.
#
# Expects OPENTS_LANGUAGE_HEADER, OPENTS_LANGUAGE_RC, and OPENTS_LANGUAGE_STRINGS_HEADER to
# be set.

if(NOT EXISTS "${OPENTS_LANGUAGE_HEADER}")
    message(FATAL_ERROR "LanguageStrings.cmake: ${OPENTS_LANGUAGE_HEADER} does not exist.")
endif()
if(NOT EXISTS "${OPENTS_LANGUAGE_RC}")
    message(FATAL_ERROR "LanguageStrings.cmake: ${OPENTS_LANGUAGE_RC} does not exist.")
endif()

file(STRINGS "${OPENTS_LANGUAGE_HEADER}" name_lines REGEX "^#define TXT_[A-Za-z0-9_]+[ \t]+[0-9]+")

set(name_to_id "")
foreach(line IN LISTS name_lines)
    string(REGEX REPLACE "^#define (TXT_[A-Za-z0-9_]+)[ \t]+([0-9]+).*$" "\\1;\\2" parts "${line}")
    list(GET parts 0 name)
    list(GET parts 1 id)
    list(APPEND name_to_id "${name}=${id}")
endforeach()

if(name_to_id STREQUAL "")
    message(FATAL_ERROR "LanguageStrings.cmake: ${OPENTS_LANGUAGE_HEADER} defines no TXT_ identifiers.")
endif()

# Read as one string rather than file(STRINGS ...) so a UTF-8 string's bytes reach the
# generated header untouched, and so a string's embedded "" (the RC escape for a literal
# quote) can be rewritten to \" in one pass per entry. The pattern has no line anchors: two
# anchored matches back to back would have to share one boundary newline, and MATCHALL never
# reuses text between matches, which silently drops every other entry.
file(READ "${OPENTS_LANGUAGE_RC}" rc_content)

# CMake's MATCHALL result and the name;text pairing built below are both CMake lists, which
# use ';' as the element separator. Escape a literal ';' in the source text first so a string
# such as "a; b" survives as one list element instead of silently splitting in two; list(GET)
# undoes the escape when a value is read back out.
string(REPLACE ";" "\\;" rc_content "${rc_content}")

string(REGEX MATCHALL "(TXT_[A-Za-z0-9_]+)[ \t]+\"((\"\"|[^\"])*)\"" rc_matches "${rc_content}")

set(entries "")
set(count 0)
foreach(match IN LISTS rc_matches)
    string(REGEX REPLACE "^(TXT_[A-Za-z0-9_]+)[ \t]+\"((\"\"|[^\"])*)\"$" "\\1;\\2" parts "${match}")
    list(GET parts 0 name)
    list(GET parts 1 text)

    set(id "")
    foreach(pair IN LISTS name_to_id)
        if(pair MATCHES "^${name}=([0-9]+)$")
            set(id "${CMAKE_MATCH_1}")
        endif()
    endforeach()
    if(id STREQUAL "")
        continue()
    endif()

    # The RC format doubles an embedded quote; C++ string literals escape it instead.
    string(REPLACE "\"\"" "\\\"" text "${text}")

    string(APPEND entries "\t{ ${id}, \"${text}\" }, // ${name}\n")
    math(EXPR count "${count} + 1")
endforeach()

if(count EQUAL 0)
    message(FATAL_ERROR "LanguageStrings.cmake: ${OPENTS_LANGUAGE_RC} defines no STRINGTABLE entries matching ${OPENTS_LANGUAGE_HEADER}.")
endif()

set(content
"/*******************************************************************************
 *                                O P E N  T S
 *******************************************************************************
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright 2026 OpenTS contributors
 *
 * See LICENSE.md for applicable additional terms and warranty disclaimers.
 ******************************************************************************/

/* Generated by cmake/LanguageStrings.cmake from language.rc. Edits are overwritten by the
 * next build. */

#pragma once

struct OpenTSLanguageString
{
	int Id;
	char const * Text;
};

inline constexpr OpenTSLanguageString OpenTSLanguageStrings[] = {
${entries}};

inline constexpr int OpenTSLanguageStringCount = ${count};
")

set(existing "")
if(EXISTS "${OPENTS_LANGUAGE_STRINGS_HEADER}")
    file(READ "${OPENTS_LANGUAGE_STRINGS_HEADER}" existing)
endif()

if(NOT existing STREQUAL content)
    file(WRITE "${OPENTS_LANGUAGE_STRINGS_HEADER}" "${content}")
endif()
