# Writes the table that maps a string identifier's name to its number, so a UI document can
# name a string the way the source does and no list is maintained by hand.
#
# The names are `#define`s in the language header, which is the one place they are declared.
# A name that appears there and nowhere else therefore reaches a document, and a name a
# document misspells is reported by the shell rather than drawn.
#
# Expects OPENTS_LANGUAGE_HEADER and OPENTS_STRING_NAME_HEADER to be set.

if(NOT EXISTS "${OPENTS_LANGUAGE_HEADER}")
    message(FATAL_ERROR "The language header ${OPENTS_LANGUAGE_HEADER} is missing.")
endif()

file(STRINGS "${OPENTS_LANGUAGE_HEADER}" LINES REGEX "^[ \t]*#define[ \t]+TXT_[A-Za-z0-9_]+[ \t]+[0-9]+")

set(ENTRIES "")
set(COUNT 0)

foreach(line IN LISTS LINES)
    string(REGEX MATCH "TXT_[A-Za-z0-9_]+" name "${line}")
    string(REGEX MATCH "[0-9]+[ \t]*$" number "${line}")
    string(STRIP "${number}" number)

    if(name AND NOT number STREQUAL "")
        string(APPEND ENTRIES "\t{ \"${name}\", ${number} },\n")
        math(EXPR COUNT "${COUNT} + 1")
    endif()
endforeach()

if(COUNT EQUAL 0)
    message(FATAL_ERROR "No string identifiers were found in ${OPENTS_LANGUAGE_HEADER}.")
endif()

set(CONTENT
"// Generated by cmake/StringNames.cmake from the language header. Do not edit.

#pragma once

struct UIStringName
{
\tchar const * Name;
\tint Identifier;
};

static UIStringName const UIStringNames[] = {
${ENTRIES}};

static int const UIStringNameCount = ${COUNT};
")

# Rewriting only on a change keeps an ordinary rebuild from recompiling every document
# consumer, the way the build identity headers do.
set(EXISTING "")
if(EXISTS "${OPENTS_STRING_NAME_HEADER}")
    file(READ "${OPENTS_STRING_NAME_HEADER}" EXISTING)
endif()

if(NOT EXISTING STREQUAL CONTENT)
    file(WRITE "${OPENTS_STRING_NAME_HEADER}" "${CONTENT}")
    message(STATUS "OpenTS: Wrote ${COUNT} string identifier names.")
endif()
